---
title: "A meta-research on the Cochrane Reviews' authors"
author: "Ahmad Sofi-Mahmudi"
date: "`r Sys.Date()`"
output: html_document
---

# Loading required packages

```{r}
pacman::p_load(dplyr,
               here,
               ggplot2,
               maps,
               stringr,
               rnaturalearth)
```


# Loading the dataset
```{r}
db <- read.csv(here("data", "cochraneauthors_db.csv"))
```

# Overall perspective

Total number of papers:
```{r}
nrow(reviews)
```

Number of papers that their authors affiliations were retrieved from Cochrane Library successfully:
```{r}
nrow(db)
```


# Country and region diversity

```{r}

```


# English-speaking diversity

## Trend
```{r}

yearly_trend <- db %>%
  select(year, first_author_english) %>%
  group_by(year) %>%
  summarise(counts = n(),
            english_speaking = sum(first_author_english == "Yes")) %>%
  mutate(p = english_speaking / counts)


p1 <-
        yearly_trend %>% 
        ggplot() +
        aes(x = year, 
            y = p) +
        geom_line(size = 0.75) +
        scale_y_continuous(limits = c(0, 1), 
                           labels = scales::percent) +
        scale_color_discrete(name = NULL) +
        labs(   title="Proportion of papers with first authors from developed English-speaking countries",
                y = "Proportion of articles (%)", 
                x = "Year") +
        theme(panel.grid.minor = element_blank(),
              legend.position = c(0.13, 0.87),
              axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1)
              )
p1
```


# Gender diversity

### Trend
```{r}

yearly_trend_gender <- db %>%
  select(year, country_1stauthor_gender) %>%
  group_by(year) %>%
  summarise(MtoF = sum(country_1stauthor_gender == "M")/sum(country_1stauthor_gender == "F"))


pg1 <-
        yearly_trend_gender %>% 
        ggplot() +
        aes(x = year, 
            y = MtoF) +
        geom_line(size = 0.75) +
        scale_color_discrete(name = NULL) +
        labs(   title="Male to female ratio for each year",
                y = "Ratio", 
                x = "Year") +
        theme(panel.grid.minor = element_blank(),
              legend.position = c(0.13, 0.87),
              axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1)
              )
pg1
```

